name = "steeler-logbook-sync"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "SYNC_DB"
database_name = "steeler_logbook_sync"
database_id = "deb8d655-2315-4c48-a112-1c07dd70c5c2"

[vars]
SYNC_OWNER_ID = "steeler"
